site_name: drf-cc-sandbox
site_description: Testing variants on authentication in DRF
repo_url: https://github.com/shearichard/drf-cc-sandbox
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/shearichard">shearichard</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
